#! /bin/bash

EXP_DIR=parsers/css/explain/out/production/css-explainer
DEPS=`ls deps/*.jar | tr '\n' ':'`
CLASSPATH=$CLASSPATH:$DEPS

# Run Java Explanation server
java -cp $CLASSPATH:$DEPS CssExplainerEntryPoint &

# Start the Python server
DJANGO_SETTINGS_MODULE=tutorons.settings.dev python manage.py runserver

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
