#! /bin/bash

EXP_DIR=parsers/css/explain/out/production/css-explainer
PY4J=$PWD/../../deps/py4j-0.8.2.jar

# Run Java Explanation server
(cd $EXP_DIR && java -cp $CLASSPATH:$PY4J CssExplainerEntryPoint) &

# Start the Python server
DJANGO_SETTINGS_MODULE=tutorons.settings.dev python manage.py runserver

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
